### ISSUE TITLE
How to deactivate auto generation of ERD?

### ISSUE THREAD

**Issue by aried3r** [voormedia/rails-erd#186]
#176 supposedly activated this, how can I deactivate it or make it conditional?

**Comment by DannyBen** [comment]
I also have the same question... sort of.

After upgrading to the latest gem version, each db migrate generates the ERD without my request.
If this is a feature that was added by design, I vote to revert to the old behavior.

Even if this is configurable, the default should be off, not on in my opinion. I wish to avoid adding any dotfile config for it.

For now, my workaround is to lock the Gemfile to the previous version with `gem 'rails-erd', "<= 1.4.4"`

**Comment by kerrizor** [comment]
:egg: on my :smile: for this one, folks. Apologies! I'll roll a fix for this as soon as I can.

**Comment by DannyBen** [comment]
:smile: excellent. Happy to see its a (minor) bug and not a feature.

**Comment by kerrizor** [comment]
One issue I have had is that I generally don't use this tool as a gem installed in my Gemfile, but as a gem installed locally, so I've had some poor process around confirming these new features really do what I expect them to. :heart: Sorry about this.

**Comment by ldonnet** [comment]
As @DannyBen glad to see it will not be a core feature.

**Comment by kerrizor** [comment]
Reverted in #191

**Comment by kerrizor** [comment]
1.4.6 reverts this :bug:

Once again, apologies for the bug!

**Comment by mitsuru** [comment]
https://github.com/voormedia/rails-erd/pull/176#issuecomment-183907800
