### ISSUE TITLE
Horizontal makes the inner boxes horizontal

### ISSUE THREAD

**Issue by sfcgeorge** [voormedia/rails-erd#218]
I have the setting `orientation: horizontal`. The graph is laid out correctly, but the inner boxes of the boxes are swizzled. Sorry for terrible description, here's a pic 😛:

<img width="314" alt="screen shot 2016-07-28 at 11 37 33" src="https://cloud.githubusercontent.com/assets/885003/17209997/ff7333b0-54b7-11e6-9c2e-04808956a0ff.png">

It never used to do this for me, it just happened the last time I regenerated my ERD. I must have updated Graphviz or something, though it doesn't look like a bleeding edge version: `dot - graphviz version 2.38.0 (20140413.2041)`. 

I'm a bit stumped really. Let me know if there's any other version or config info that would help.

**Comment by sebroeder** [comment]
I can confirm this problem.

I use `graphviz version 2.40.1 (20161225.0304)` installed via homebrew (default options) on macOS 10.12.3.
I use the `ruby-graphviz` gem in version `1.2.2`.

**Comment by sebroeder** [comment]
I had a look at the documentation of Graphviz’ dot language and found a paragraph that I think is relevant to the problem here:

> Visually, a record is a box, with fields represented by alternating rows of horizontal or vertical subboxes. The Mrecord shape is identical to a record shape, except that the outermost box has rounded corners. Flipping between horizontal and vertical layouts is done by nesting fields in braces "{...}". The top-level orientation in a record is horizontal. Thus, a record with label "A | B | C | D" will have 4 fields oriented left to right, while "{A | B | C | D}" will have them from top to bottom and "A | { B | C } | D" will have "B" over "C", with "A" to the left and "D" to the right of "B" and "C".
>
> The initial orientation of a record node depends on the rankdir attribute. If this attribute is TB (the default) or BT, corresponding to vertical layouts, the top-level fields in a record are displayed horizontally. If, however, this attribute is LR or RL, corresponding to horizontal layouts, the top-level fields are displayed vertically.

Source: http://www.graphviz.org/doc/info/shapes.html#record

I switched the output format to dot and investigated the markup. This is how a sample erd with horizontal layout looks like: 

```dot
digraph HorizontalExample {
rankdir = "LR";
ranksep = "0.5";
nodesep = "0.4";
pad = "0.4,0.4";
margin = "0,0";
concentrate = "true";
labelloc = "t";
fontsize = "13";
fontname = "Arial BoldMT";
node[ shape  =  "Mrecord" , fontsize  =  "10" , fontname  =  "ArialMT" , margin  =  "0.07,0.05" , penwidth  =  "1.0"];
edge[ fontname  =  "ArialMT" , fontsize  =  "7" , dir  =  "both" , arrowsize  =  "0.9" , penwidth  =  "1.0" , labelangle  =  "32" , labeldistance  =  "1.8"];
rankdir = "TB";
label = "Horizontal example\n\n";
m_Example [label = <<table border="0" align="center" cellspacing="0.5" cellpadding="0" width="134">
  <tr><td align="center" valign="bottom" width="130"><font face="Arial BoldMT" point-size="11">HorizontalExample</font></td></tr>
</table>
|
<table border="0" align="left" cellspacing="2" cellpadding="0" width="134">
  <tr><td align="left" width="130" port="alpha">alpha <font face="Arial ItalicMT" color="grey60">string</font></td></tr>
  <tr><td align="left" width="130" port="beta">beta <font face="Arial ItalicMT" color="grey60">string</font></td></tr>
  <tr><td align="left" width="130" port="gamma">gamma <font face="Arial ItalicMT" color="grey60">boolean</font></td></tr>
</table>
>];
}
```

The layout of the rendered PDF is is obviously broken:

```bash
dot -Tpdf -O example_horizontal_broken.dot
```
 
![example_horizontal_broken.dot.pdf](https://github.com/voormedia/rails-erd/files/758858/example_horizontal_broken.dot.pdf)

When I wrap the two `table`s, that are separated by the `|` sign, in `{ }`, as the snippet from the documentation indicates, the problem is indeed fixed:

```dot
digraph HorizontalExample {
rankdir = "LR";
ranksep = "0.5";
nodesep = "0.4";
pad = "0.4,0.4";
margin = "0,0";
concentrate = "true";
labelloc = "t";
fontsize = "13";
fontname = "Arial BoldMT";
node[ shape  =  "Mrecord" , fontsize  =  "10" , fontname  =  "ArialMT" , margin  =  "0.07,0.05" , penwidth  =  "1.0"];
edge[ fontname  =  "ArialMT" , fontsize  =  "7" , dir  =  "both" , arrowsize  =  "0.9" , penwidth  =  "1.0" , labelangle  =  "32" , labeldistance  =  "1.8"];
rankdir = "TB";
label = "Horizontal example\n\n";
m_Example [label = <{<table border="0" align="center" cellspacing="0.5" cellpadding="0" width="134">
  <tr><td align="center" valign="bottom" width="130"><font face="Arial BoldMT" point-size="11">HorizontalExample</font></td></tr>
</table>
|
<table border="0" align="left" cellspacing="2" cellpadding="0" width="134">
  <tr><td align="left" width="130" port="alpha">alpha <font face="Arial ItalicMT" color="grey60">string</font></td></tr>
  <tr><td align="left" width="130" port="beta">beta <font face="Arial ItalicMT" color="grey60">string</font></td></tr>
  <tr><td align="left" width="130" port="gamma">gamma <font face="Arial ItalicMT" color="grey60">boolean</font></td></tr>
</table>
}>];
}
```

```bash
dot -Tpdf -O example_horizontal_fixed.dot
```

![example_horizontal_fixed.dot.pdf](https://github.com/voormedia/rails-erd/files/758866/example_horizontal_fixed.dot.pdf)

I’ll try to come up with a failing test case and an actual fix as soon as I can.

**Comment by kerrizor** [comment]
@sebroeder Awesome investigation work! Thank you!

**Comment by sebroeder** [comment]
@kerrizor I found the code in the ERB templates that is responsible for inserting the curly braces and there are already existing tests. The root cause of this issue is that the code and tests were not updated when the meaning of `orientation: horizontal` and `orientation: vertical` was swapped recently. When I adjusted the templates, only 3 of the 4 related tests failed, so there is one test that is not testing what I is supposed to test. I need to have another look at the very cryptic regular expressions used in the tests and hope to replace them with more literal strings, that are easier to comprehend. I hope I can find some time to finish this soon. The fixed templates work fine for me locally, it's just the tests that need work.
