### ISSUE TITLE
rails aborted! Unable to find GraphViz's "dot" executable.

### ISSUE THREAD

**Issue by alphamuth** [voormedia/rails-erd#318]
I am getting the error `rails aborted!
Unable to find GraphViz's "dot" executable.` please help

**Comment by gugat** [comment]
I got the same error in MacOS Mojave, where GraphViz doesn't build.   [Saw it at GraphViz site](https://graphviz.gitlab.io/download/) 

![image](https://user-images.githubusercontent.com/648495/54165911-79e31900-4441-11e9-94ec-6e9237ab5d88.png)

**Comment by kerrizor** [comment]
Sorry you're running into this! I haven't experienced it myself, but I've also been bootstrapping this Mac up from previous OSX releases. I'm going to go ahead and close this for now, since it isn't really something related specifically to this project, but if you get any updates _PLEASE_ drop them in here!
